export const questions = [
    {
      id: 1,
      type: "mcq",
      question: "What is the correct syntax to import a React component?",
      options: [
        "import React.Component from 'react'",
        "import { Component } from 'react'",
        "require('Component')",
        "import React from 'react-dom'",
      ],
      answer: "import { Component } from 'react'",
    },
    {
      id: 2,
      type: "mcq",
      question: "What does JSX stand for?",
      options: [
        "Java Syntax Extension",
        "JavaScript Extension",
        "JavaScript XML",
        "JSON Syntax",
      ],
      answer: "JavaScript XML",
    },
    {
      id: 3,
      type: "mcq",
      question: "Which hook is used to manage state in a functional component?",
      options: ["useEffect()", "useContext()", "useState()", "useReducer()"],
      answer: "useState()",
    },
    {
      id: 4,
      type: "mcq",
      question: "In React, what is the purpose of keys in lists?",
      options: [
        "To uniquely identify DOM elements",
        "To provide performance tips",
        "To track user input",
        "To validate props",
      ],
      answer: "To uniquely identify DOM elements",
    },
    {
      id: 5,
      type: "mcq",
      question: "What is the default value of useState() when no argument is passed?",
      options: ["null", "undefined", "0", '""'],
      answer: "undefined",
    },
    {
      id: 6,
      type: "mcq",
      question: "Which of the following is NOT a lifecycle method in class components?",
      options: [
        "componentDidMount()",
        "render()",
        "useEffect()",
        "componentWillUnmount()",
      ],
      answer: "useEffect()",
    },
    {
      id: 7,
      type: "mcq",
      question: "What is the use of useEffect() in React?",
      options: [
        "Handle events",
        "Manipulate DOM",
        "Perform side effects like API calls",
        "Update state",
      ],
      answer: "Perform side effects like API calls",
    },
    {
      id: 8,
      type: "mcq",
      question: "Which of these best describes a React component?",
      options: [
        "A function or class that optionally accepts input and returns a React element",
        "A HTML element",
        "A database query",
        "An AJAX request",
      ],
      answer: "A function or class that optionally accepts input and returns a React element",
    },
    {
      id: 9,
      type: "mcq",
      question: "Which of the following correctly updates state in React?",
      options: [
        'this.state.name = "John"',
        'setState({name: "John"})',
        'this.setState(name = "John")',
        'state.name = "John"',
      ],
      answer: 'setState({name: "John"})',
    },
    {
      id: 10,
      type: "mcq",
      question: "What is the virtual DOM in React?",
      options: [
        "A direct representation of the UI in the database",
        "A JavaScript representation of the actual DOM",
        "A real copy of the DOM in memory",
        "A plugin for React",
      ],
      answer: "A JavaScript representation of the actual DOM",
    },
    {
      id: 11,
      type: "truefalse",
      question: "Props in React can be changed within a component.",
      options: ["True", "False"],
      answer: "False",
    },
    {
      id: 12,
      type: "truefalse",
      question: "React components must return a single parent element.",
      options: ["True", "False"],
      answer: "True",
    },
    {
      id: 13,
      type: "truefalse",
      question: "React uses a two-way data binding model.",
      options: ["True", "False"],
      answer: "False",
    },
    {
      id: 14,
      type: "truefalse",
      question: "useState can only be used inside functional components.",
      options: ["True", "False"],
      answer: "True",
    },
    {
      id: 15,
      type: "truefalse",
      question: "React is maintained by Microsoft.",
      options: ["True", "False"],
      answer: "False",
  },
  {
    id: 16,
    type: "mcq",
    question: "Which command is used to create a new React app using Create React App?",
    options: [
      "npm init react-app my-app",
      "npx create-react-app my-app",
      "react new my-app",
      "create-react-app my-app",
    ],
    answer: "npx create-react-app my-app",
  },
  {
    id: 17,
    type: "mcq",
    question: "What is the correct way to pass props to a child component?",
    options: [
      "<Child props='value' />",
      "<Child value='props' />",
      "<Child value='value' />",
      "<Child prop=value />",
    ],
    answer: "<Child value='value' />",
  },
  {
    id: 18,
    type: "mcq",
    question: "Which method is used to render a React component into the DOM?",
    options: [
      "React.mount()",
      "ReactDOM.render()",
      "renderDOM()",
      "React.attach()",
    ],
    answer: "ReactDOM.render()",
  },
  {
    id: 19,
    type: "mcq",
    question: "What does the 'key' prop help React identify?",
    options: [
      "The parent component",
      "The unique element in a list",
      "The prop type",
      "The event handler",
    ],
    answer: "The unique element in a list",
  },
  {
    id: 20,
    type: "mcq",
    question: "Which hook is used to access context in a functional component?",
    options: [
      "useState()",
      "useEffect()",
      "useContext()",
      "useRef()",
    ],
    answer: "useContext()",
  },
  {
    id: 21,
    type: "truefalse",
    question: "You can have multiple useEffect hooks in a single component.",
    options: ["True", "False"],
    answer: "True",
  },
  {
    id: 22,
    type: "truefalse",
    question: "useReducer is an alternative to useState for managing complex state logic.",
    options: ["True", "False"],
    answer: "True",
  },
  {
    id: 23,
    type: "truefalse",
    question: "React Router is used for styling React components.",
    options: ["True", "False"],
    answer: "False",
  },
  {
    id: 24,
    type: "truefalse",
    question: "JSX allows you to write HTML in JavaScript files.",
    options: ["True", "False"],
    answer: "True",
  },
  {
    id: 25,
    type: "truefalse",
    question: "React fragments can be used to group multiple elements without adding extra nodes to the DOM.",
    options: ["True", "False"],
    answer: "True",
  },
  {
    id: 26,
    type: "mcq",
    question: "What is the purpose of useRef in React?",
    options: [
      "To store a mutable value that does not cause a re-render",
      "To re-render the component",
      "To declare state",
      "To perform side effects",
    ],
    answer: "To store a mutable value that does not cause a re-render",
  },
  {
    id: 27,
    type: "mcq",
    question: "What’s the purpose of React.StrictMode?",
    options: [
      "To enable faster performance",
      "To render components in production mode",
      "To highlight potential problems in an application",
      "To compile the app",
    ],
    answer: "To highlight potential problems in an application",
  },
  {
    id: 28,
    type: "mcq",
    question: "Which hook would you use to run code after the component has rendered?",
    options: ["useState()", "useEffect()", "useRef()", "useMemo()"],
    answer: "useEffect()",
  },
  {
    id: 29,
    type: "mcq",
    question: "How can you prevent a re-render in a functional component?",
    options: [
      "By using a class component",
      "By using React.memo",
      "By using a reducer",
      "By using state",
    ],
    answer: "By using React.memo",
  },
  {
    id: 30,
    type: "truefalse",
    question: "React Native is the same as React.",
    options: ["True", "False"],
    answer: "False",
  },

  ];
  