export const questions = [
    {
      id: 1,
      type: "mcq",
      question: "What is the correct syntax to import a React component?",
      options: [
        "import React.Component from 'react'",
        "import { Component } from 'react'",
        "require('Component')",
        "import React from 'react-dom'",
      ],
      answer: "import { Component } from 'react'",
    },
    {
      id: 2,
      type: "mcq",
      question: "What does JSX stand for?",
      options: [
        "Java Syntax Extension",
        "JavaScript Extension",
        "JavaScript XML",
        "JSON Syntax",
      ],
      answer: "JavaScript XML",
    },
    {
      id: 3,
      type: "mcq",
      question: "Which hook is used to manage state in a functional component?",
      options: ["useEffect()", "useContext()", "useState()", "useReducer()"],
      answer: "useState()",
    },
    {
      id: 4,
      type: "mcq",
      question: "In React, what is the purpose of keys in lists?",
      options: [
        "To uniquely identify DOM elements",
        "To provide performance tips",
        "To track user input",
        "To validate props",
      ],
      answer: "To uniquely identify DOM elements",
    },
    {
      id: 5,
      type: "mcq",
      question: "What is the default value of useState() when no argument is passed?",
      options: ["null", "undefined", "0", '""'],
      answer: "undefined",
    },
    {
      id: 6,
      type: "mcq",
      question: "Which of the following is NOT a lifecycle method in class components?",
      options: [
        "componentDidMount()",
        "render()",
        "useEffect()",
        "componentWillUnmount()",
      ],
      answer: "useEffect()",
    },
    {
      id: 7,
      type: "mcq",
      question: "What is the use of useEffect() in React?",
      options: [
        "Handle events",
        "Manipulate DOM",
        "Perform side effects like API calls",
        "Update state",
      ],
      answer: "Perform side effects like API calls",
    },
    {
      id: 8,
      type: "mcq",
      question: "Which of these best describes a React component?",
      options: [
        "A function or class that optionally accepts input and returns a React element",
        "A HTML element",
        "A database query",
        "An AJAX request",
      ],
      answer: "A function or class that optionally accepts input and returns a React element",
    },
    {
      id: 9,
      type: "mcq",
      question: "Which of the following correctly updates state in React?",
      options: [
        'this.state.name = "John"',
        'setState({name: "John"})',
        'this.setState(name = "John")',
        'state.name = "John"',
      ],
      answer: 'setState({name: "John"})',
    },
    {
      id: 10,
      type: "mcq",
      question: "What is the virtual DOM in React?",
      options: [
        "A direct representation of the UI in the database",
        "A JavaScript representation of the actual DOM",
        "A real copy of the DOM in memory",
        "A plugin for React",
      ],
      answer: "A JavaScript representation of the actual DOM",
    },
    {
      id: 11,
      type: "truefalse",
      question: "Props in React can be changed within a component.",
      options: ["True", "False"],
      answer: "False",
    },
    {
      id: 12,
      type: "truefalse",
      question: "React components must return a single parent element.",
      options: ["True", "False"],
      answer: "True",
    },
    {
      id: 13,
      type: "truefalse",
      question: "React uses a two-way data binding model.",
      options: ["True", "False"],
      answer: "False",
    },
    {
      id: 14,
      type: "truefalse",
      question: "useState can only be used inside functional components.",
      options: ["True", "False"],
      answer: "True",
    },
    {
      id: 15,
      type: "truefalse",
      question: "React is maintained by Microsoft.",
      options: ["True", "False"],
      answer: "False",
    },
  ];
  